server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.raybvdyfljopcfnhxiaq
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

ai-server:
  base-url: ${AI_SERVER_URL:http://localhost:8000}
  internal-api-key: ${AI_INTERNAL_API_KEY}
  connect-timeout: 3s
  read-timeout: 10s

llm-server:
#  base-url: ${LLM_SERVER_URL:https://prevalent-dance-sculpture.ngrok-free.dev}
  base-url: ${LLM_SERVER_URL:http://localhost:8001}
  connect-timeout: 3s
  read-timeout: 600s
