server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
    username: postgres.ozcdarfrstpmwvjkcoqe
    password: "16's_aivle_"
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
