server:
  port: 8080

spring:
  datasource:
#    Direct connection
#    url: jdbc:postgresql://db.ozcdarfrstpmwvjkcoqe.supabase.co:5432/postgres?sslmode=require
#    username: postgres
#    password: "16's_aivle_"
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.ozcdarfrstpmwvjkcoqe
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
