server:
  port: 8080

spring:
  datasource:
#    url: jdbc:postgresql://db.ozcdarfrstpmwvjkcoqe.supabase.co:5432/postgres?sslmode=require
##    url: jdbc:postgres?ql://aws-0-ap-southeast-2:pooler:supabase:com:5432/postgres
#    username: postgres
#    password: "16's_aivle_"
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres
    username: postgres.ozcdarfrstpmwvjkcoqe
    password: "16's_aivle_"
    driver-class-name: org.postgresql.Driver

  
  jpa:
    hibernate:
      ddl-auto: validation
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
