server:
  port: 8080
aws:
  s3:
    region: ${AWS_REGION:ap-northeast-2}
spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.raybvdyfljopcfnhxiaq
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

ai-gateway:
  base-url: ${AI_GATEWAY_URL:http://localhost:8081}
  internal-api-key: ${AI_INTERNAL_API_KEY}
  connect-timeout: 3s
  read-timeout: 10s

  callback-url: ${BACKEND_CALLBACK_URL:http://localhost:8080/internal/ai/callbacks/cell}

AWS_S3_BUCKET: "kt-aivle-big-proj-kks"
