dependencies {
    implementation project(':module-core')
    implementation 'org.springframework.boot:spring-boot-starter-web' // WebClient 사용 목적
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
//    implementation 'org.springframework.ai:spring-ai-starter-vector-store-mongodb-atlas'
}